import { readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

type Asset = { path: string; mode?: number }

const assets: Asset[] = [
  // Workflows
  { path: "smithers-runner/workflow.tsx" },
  { path: "smithers-runner/workflow-dynamic.tsx" },
  { path: "smithers-runner/smithers.ts" },
  { path: "smithers-runner/package.json" },
  // Old scripts (for backward compat)
  { path: "scripts/validate-specs.ts" },
  { path: "scripts/minify-specs.ts" },
  // Prompts
  { path: "prompts/DEFAULT-IMPLEMENTER.md" },
  { path: "prompts/DEFAULT-REVIEWER.md" },
  { path: "prompts/reviewers/SECURITY.md" },
  { path: "prompts/reviewers/CODE-QUALITY.md" },
  { path: "prompts/reviewers/SIMPLICITY.md" },
  { path: "prompts/reviewers/TEST-COVERAGE.md" },
  { path: "prompts/reviewers/MAINTAINABILITY.md" },
  { path: "prompts/reviewers/TIGERSTYLE.md" },
  { path: "prompts/reviewers/CORRECTNESS-GUARANTEES.md" },
  { path: "prompts/reviewers/production-monitoring.md" },
  { path: "prompts/reviewers/nasa-10-rules.md" },
  { path: "prompts/reviewers/guarantee-hierarchy.md" },
  // Docs
  { path: "README.md" },
  { path: "WORKFLOW.md" },
  { path: "LEARNINGS.md" },
  { path: "OBSERVABILITY.md" },
  { path: "QUICKSTART.md" },
  { path: "specs/README.md" }
]

const repoRoot = resolve(process.cwd())
const outPath = join(repoRoot, "src", "fabrik", "embeddedAssets.ts")

const lines = assets.map((asset) => {
  const abs = join(repoRoot, asset.path)
  const contents = readFileSync(abs, "utf8")
  const mode = asset.mode ? `, mode: ${asset.mode}` : ""
  return `{ path: ${JSON.stringify(asset.path)}, contents: ${JSON.stringify(contents)}${mode} }`
})

const output = `// Generated by scripts/embed-assets.ts. Do not edit.
export type EmbeddedAsset = { path: string; contents: string; mode?: number }

export const embeddedAssets: EmbeddedAsset[] = [
  ${lines.join(",\n  ")}
]
`

writeFileSync(outPath, output, "utf8")
