import { readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

type Asset = { path: string; mode?: number }

const assets: Asset[] = [
  { path: "scripts/dispatch.sh", mode: 0o755 },
  { path: "scripts/cleanup-workdirs.sh", mode: 0o755 },
  { path: "scripts/record-human-feedback.sh", mode: 0o755 },
  { path: "scripts/smithers-fleet.sh", mode: 0o755 },
  { path: "scripts/smithers-spec-runner.tsx" },
  { path: "scripts/smithers-reviewer.tsx" },
  { path: "scripts/validate-specs.ts" },
  { path: "scripts/minify-specs.ts" },
  { path: "prompts/DEFAULT-IMPLEMENTER.md" },
  { path: "prompts/DEFAULT-REVIEWER.md" },
  { path: "prompts/reviewers/SECURITY.md" },
  { path: "prompts/reviewers/CODE-QUALITY.md" },
  { path: "prompts/reviewers/SIMPLICITY.md" },
  { path: "prompts/reviewers/TEST-COVERAGE.md" },
  { path: "prompts/reviewers/MAINTAINABILITY.md" },
  { path: "README.md" },
  { path: "WORKFLOW.md" },
  { path: "QUICKSTART.md" },
  { path: "specs/README.md" }
]

const repoRoot = resolve(process.cwd())
const outPath = join(repoRoot, "src", "fabrik", "embeddedAssets.ts")

const lines = assets.map((asset) => {
  const abs = join(repoRoot, asset.path)
  const contents = readFileSync(abs, "utf8")
  const mode = asset.mode ? `, mode: ${asset.mode}` : ""
  return `{ path: ${JSON.stringify(asset.path)}, contents: ${JSON.stringify(contents)}${mode} }`
})

const output = `// Generated by scripts/embed-assets.ts. Do not edit.
export type EmbeddedAsset = { path: string; contents: string; mode?: number }

export const embeddedAssets: EmbeddedAsset[] = [
  ${lines.join(",\n  ")}
]
`

writeFileSync(outPath, output, "utf8")
